dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - KONG_VERSION=chore/ci-pinning
    - KONG_PLUGINS=bundled,request-transformer
    - KONG_TEST_PLUGINS=bundled,request-transformer

install:
  - git clone --recursive --single-branch --branch chore/ci-pinning https://github.com/Kong/kong.git ~/kong
  - export PATH=$PATH:/usr/local/openresty/bin/:/usr/local/kong/bin/:/usr/local/openresty/nginx/sbin/
  - pushd ~/kong; make setup-env; popd
  - docker run -d --name=cassandra --rm -p 7199:7199 -p 7000:7000 -p 9160:9160 -p 9042:9042 cassandra:3.9
  - docker run -d --name=postgres --rm -p 5432:5432 postgres:9

script:
  - luacheck .
  - pushd ~/kong; bin/busted -o gtest -v --exclude-tags=flaky,ipv6 $TRAVIS_BUILD_DIR/spec

