dist: focal
jobs:
  include:
  - name: Kong CE 2.0.x
    env: KONG_VERSION=2.0.x
  - name: Kong CE 2.1.x
    env: KONG_VERSION=2.1.x
  - name: Kong CE 2.2.x
    env: KONG_VERSION=2.2.x
  - name: Enterprise 2.1.4.x
    env: KONG_VERSION=2.1.4.x
  - name: Enterprise 2.2.0.x
    env: KONG_VERSION=2.2.0.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee POSTGRES=latest CASSANDRA=latest
env:
  global:
  # for Enterprise images
  - PULP_USERNAME=admin
  - secure: Pr2465dOELvOogXcqwzr8ytq1wjzROkt5jM7C4QB8eTkLzEWm922hs84o1E3cHJLcqCyKaY+4VCgaAGB0iHeV9Kc2J8yvROa3YdmI9AF8TqNNACumMPSsS2kZE5Hr/jXaP9JqRCa84ZDPCgGnXnFIi55GdosQh6oEYisdcflPAD+o61cx9fUsj/vHw/gSFb/9tZ8RR1yDI/qunc382495MnC+OuqUdeP5ZgXABrs1KI7C6cWZWGX+RwYn+E1HkjYkEr3CabBDMzKNvkBR2sWOw8BhmcOyIOZYPxlhOoxTnmcS8r4/bdglUJ/ZGFtONweobE+zYYv8zv6Li2CbQIPDMWz4u60TGYn65mEyPmqFU/jm0EbR9VJ9k3TDt3HElmSqGlgvRtND9BUp11hNQz+wCcVWyc3frJyiWBGG+nOxeN3tPiBWOL29A9f3FhVRDBMT70qZLGCIAGl4BtJvmQ/ExVoOKRWnS1XH12XYUR8vfQJqFqOsu8/hxZv+evagBul8ErJB4NZFEY87pYe9naVJUDfqBOHnxPV/QZicD2TvBecgWdk+/5RZMSQBVKYD8cLJwU6VlNC0QyQ6nQrXPlOxGlQaTuvjFI0cmpE+bJKFRfohkzA5BgNFHDJWVyEyZ7DVjMK74faPr+lqELZnBYgBSCMlhE4Nh6jtDmGo6FG1bY=
  # for Enterprise nightly images
  - DOCKER_USERNAME=kongcloudpull
  - secure: EzPrLUd0m7XxbQlnzzMHP9zQVngONbtwv0nvNp5JkDIY51DwgbnUG5cnIB6XGqeewIspMsoBQP8IZPjY2hd0ZZrf3SK8PYU6oBIA4eqm1auCMF6bnwgBMGpLmalfwt9STGNUbD5wbFhGUsU8lBBvUPovjAJm8BDwRNAm59NPxC6GymG/nygE/bPr4RP9FiyBQ2tqYOW1+J6BVx29+Djn2brYgCu8C+05xwt9KVSBWrItLg2V/45w8qPOpOSuFwnS3Y0l5pC1xh0cX9pBjLlKbbdufMm00yMQnb3iQ6h32QBoiu5NRWFq6zWKzZXE/oVNUqOMF+YeUzN2+XC3sExcrFVe26/8Ajh2N7DyNyRPuk/+W6igrNOP4iL6qqRomoOmKU6MBY9pYeFjNPuxw9pgJUPVfGGxLXS4dTbQJcvgu8YDqE/btZturgW1/H8EC5bF9mdSdVc6JdckmBhHHHcurWv8zzL1dYfKqdqWnyAbmtFjDaw8uhOxdjUZqENQS8gmIucRjLwBcqdrLhadYzFxPjI3EAeMMAM/UpT225+dMlGXU6j6Wnhq1/cyPYys9pikgiHGFSY4KdSzFfBIvCeEefcJNI0GRFsJugqfhdhHsMpyI/3VteGWP003WS1GD2dvcglxkUD4tHeBnYqf8XND4PX9yWR1DoBjzvlVJV84iLE=
install:
- echo "$DOCKER_KEY" | docker login -u "$DOCKER_USER" --password-stdin
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"
script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"
notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: H7cwgmVIQGH4zIjwUdPEmEBCbnP0K696lEjx2g2L35uj4r9qt/3iwLzNLURTmz/R5Jlo6NZypCL8Zcv4ujSuh7UR1P/ob53Ca8az9y0vZsjz68HRrQ1UM9CljEN5Y/8F2J69wtfjx52LNC6BGVov0IyXTnUI/cLPylbgmyJoguUKnlsFo1WYn357R6dNwHS5n6jKAgGETvkhO1QCZuS15YX0BGIQw4Wt1OV1b/1T9Gm7JGLz51VrGig4G+V8mem040hju+wxJpKAcwxMqBhB/onu88CQjYjpVN2vHY5WTEdWCPjCU+BBAMGeiKt1nJVr5GQKFFdhvr8gmECSi7QKOi14kt40+1YUbq3ZwemZyTcIucFlMkvaGvOvDl8dRbPAe3Vy8Yh7hQAnFHdlVyYyfr0Tw5qnJrpDLVspmSbCy3J+vsafrEhXKQAsOhyU0ANmyEt0tJiXPA5DMQph/oACF24GIzlARDDfFvknGlXjA4D1VCtVUy90OWtQPBoNBinLAth60P5wIGF0k6/LX1I6iv+sJyCFlnCagVtzJI51frCU3rpg5K5CLUMvD11kTiZ8v61IVQrCahUkWfHYHl5dy7iDb9TdYoKSj1vPee/IYt4bOlPsECSMshIXAsz3cZfn2RLJhOBPEWzpdPiobpjST1+NACJUkD5qRZQBw6gknfg=
